//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public Cars()
        {
            this.Booking = new HashSet<Booking>();
            this.Specifications = new HashSet<Specifications>();
            this.Specifications1 = new HashSet<Specifications>();
        }
    
        public int id { get; set; }
        public string model { get; set; }
        public decimal PricePerHour { get; set; }
        public string number { get; set; }
        public string color { get; set; }
        public decimal FuelConsumption { get; set; }
        public int NumberOfSeats { get; set; }
        public string CarClass { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual ICollection<Specifications> Specifications { get; set; }
        public virtual ICollection<Specifications> Specifications1 { get; set; }
    }
}
