//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string inn { get; set; }
        public string addres { get; set; }
        public string phone { get; set; }
        public bool salesman { get; set; }
        public bool buyer { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
    }
}
