//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preperation
    {
        public Preperation()
        {
            this.Specifications = new HashSet<Specifications>();
        }
    
        public int id { get; set; }
        public string material { get; set; }
        public string unit { get; set; }
        public int quantity { get; set; }
    
        public virtual ICollection<Specifications> Specifications { get; set; }
    }
}
