//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public Price()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int id { get; set; }
        public string material { get; set; }
        public decimal price1 { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
    }
}
