//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsharingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifications
    {
        public int id { get; set; }
        public int Cars_id { get; set; }
        public int Preperation_id { get; set; }
        public string unit { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public decimal cost { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Cars Cars1 { get; set; }
        public virtual Preperation Preperation { get; set; }
    }
}
